import Head from 'next/head';

function HeadComponent() {
  return (
    <Head>
      <title>Smart Biblía 2.0</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default HeadComponent;
